version: "2"

services:
  backend:
    container_name: backend
    build: backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data:
