create table users
(
    id         bigint generated by default as identity,
    email      varchar(255) not null,
    username   varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    publicity  integer      not null,
    password   varchar(255) not null,
    role_admin boolean      not null,
    role_moder boolean      not null,
    primary key (id)
);
